# Generated by Django 4.2.6 on 2023-10-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='backend_lang',
        ),
        migrations.DeleteModel(
            name='card',
        ),
        migrations.DeleteModel(
            name='core_lang',
        ),
        migrations.DeleteModel(
            name='front_lang',
        ),
        migrations.DeleteModel(
            name='hero_image',
        ),
        migrations.DeleteModel(
            name='hero_information',
        ),
        migrations.DeleteModel(
            name='serviec_heading',
        ),
    ]
