# Generated by Django 4.1.7 on 2023-10-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_button_text',
            field=models.TextField(),
        ),
    ]
