# Generated by Django 4.1.7 on 2023-10-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_card_card_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='lets_cofee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
